apiVersion: apps/v1
kind: Deployment
metadata:
  name: legal-app
  namespace: production
  labels:
    app: legal-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: legal-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: legal-app
    spec:
      containers:
      - name: legal-app
        image: username/legal-app:latest
        ports:
        - containerPort: 8501
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: db_host
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: db_name
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: db_user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: db_password
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: openai_api_key
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 5
          periodSeconds: 5
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      imagePullSecrets:
      - name: dockerhub-secret 