apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: production
type: Opaque
data:
  # 実際のデプロイ時には、これらの値はbase64エンコードされた実際のシークレットに置き換えてください
  db_password: cGFzc3dvcmQ=  # "password"のbase64エンコード
  openai_api_key: c2stYWJjMTIzNDU2Nzg5MA==  # "sk-abc1234567890"のbase64エンコード 